name: Selenium Tests - Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t selenium-pom:test .

      - name: Run Selenium tests
        run: docker run --name selenium-test selenium-pom:test pytest --browser=chrome --env=qa

      - name: Copy reports
        if: always()
        run: docker cp selenium-test:/app/reports ./reports

      - name: Copy screenshots
        if: always()
        run: |
          docker cp selenium-test:/app/screenshots ./screenshots || true

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: |
            reports/
            screenshots/
          if-no-files-found: ignore